name: Daily Python Script

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 6:00 AM UTC
  workflow_dispatch:     # Allows manual trigger via GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # or whichever version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: python main.py
